on:
  workflow_call:

jobs:
  repo-sync:
    name: Repository sync from Template
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v2
        with:
          source_repo_path: PrinsFrank/php-package-template
